### ISSUE TITLE
소셜로그인 오류 수정

### ISSUE THREAD

**Issue by jh10253267** [hobby-hop/hobby-hop#328]
프론트에서 테스트했을 때 배포 백엔드 주소가 아닌 localhost로 리다이렉트되는 문제를 발견함.
코드를 보니 리다이렉트 url이 localhost로 설정되어있는 것을 확인
* [ ] KakaoService url 수정
* [ ] 테스트
여러 문제로 서버를 닫은 상태라 테스트가 어려워 보류
Actions Runner의 공식문서에 따르면 14일 이상 사용되지 않았을 경우 자원이 해제된다. 계속 유지시키기 위해선 14일 주기로 배포가 나가야하는데 좀 힘들 것 같고 비용 문제 와 EC2메모리 문제로 인해 서버를 닫은 상태.

**Comment by kkamjjing2** [comment]
헐 이걸 찾으시다니... 진짜 감사합니다 제가 짰는데 전혀 몰랐네요...!
